# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - pip install mkdocs mkdocs-rtd-dropdown mkdocstrings[python]

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

mkdocs:
   configuration: mkdocs.yml