name: sdrips_env
channels:
  - defaults
  - conda-forge
dependencies:
  - beautifulsoup4
  - cartopy
  - colorlog
  - contextily
  - ee
  - filelock
  - geemap
  - geopandas
  - geopy
  - google-cloud-resource-manager
  - matplotlib
  - networkx
  - numpy
  - pandas
  - paramiko
  - pycrs
  - pykrige
  - pyproj
  - pytest
  - PyYAML
  - rasterio
  - Requests
  - rioxarray
  - ruamel.yaml
  - scikit_learn
  - scipy
  - setuptools
  - Shapely
  - tqdm
  - xarray
