site_name: sDRIPS Documentation
site_url: https://sdrips.readthedocs.io/
site_author: Shahzaib Khan 
repo_url: https://github.com/shahzaib1007/sDRIPS
nav:
  - Home: index.md
  - API Reference:
      - sdrips: api/sdrips.md

theme:
  name: readthedocs
  logo: images/sDRIPS_Logo/Logo.png
  include_homepage_in_sidebar: true
  highlightjs: true
  hljs_languages:
        - yaml
        - rust
  features:
    - content.code.copy  
    - content.tabs.link
    - content.admonitions
    - search.suggest
  icon:
    admonition:
      success: fontawesome/solid/check
      warning: fontawesome/solid/triangle-exclamation
  analytics:
    provider: google
    property: G-5C11Q4TSHT

docs_dir: docs
site_dir: site
use_directory_urls: true
markdown_extensions:
  - admonition
  - mdx_math
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
plugins:
    - search:
        prebuild_index: true
        indexing: full
        lang: en
    - mkdocstrings:
        handlers:
        python:
            paths: [src] 
            options:
            show_source: true
    - mkdocs-jupyter:       
        execute: false     
        include_source: true
copyright: Developed by <a href="https://shahzaib1007.github.io/">Shahzaib Khan</a> <br> Copyright &copy; 2025, <a href="https://saswe.net/">University of Washington SASWE Research Group</a>
docs_dir: docs
site_dir: site
use_directory_urls: true

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true

extra_css:
  - css/custom.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
# Main pages
- Home:
    - 'sDRIPS': 'index.md'
    - 'Motivation': 'Motivation/motivation.md'
- Model:
    - 'Conceptual Model': 'Model/ConceptualModel.md'
    - 'Computational Model': 'Model/ComputationalModel.md'
- Quick Start: 
    - 'Getting Ready': 'Quick_Start/Getting_ready.md'
    - 'Installation Guide': 'Quick_Start/Installation.md'
- Configuration:
    - 'Script Configuration File': 'Configuration/script_config.md'
    - 'Crop Configuration File': 'Configuration/crop_config.md'
    - 'Command Area Configuration File': 'Configuration/command_area_config.md'
    - 'Configuration Links File': 'Configuration/config_links.md'
    - 'Secrets File': 'Configuration/secrets.md'
- Data Description:
    - 'Directory Structure': 'Directory/Directory.md'
    - 'Data Used': 'Directory/Data_Used.md'
- Tutorials:
    - Creating Command Areas (Optional):
        - Command Line Interface: tutorials/cmd_area_creation/cli.md
        - Notebook: tutorials/cmd_area_creation/Creating_CMD_Config.ipynb
    - Creating Command Area Config Files:
        - Command Line Interface: tutorials/config_files/cli.md
        - Notebook: tutorials/config_files/Creating_CMD_Config.ipynb
    
- Application:
    - 'sDRIPS-Sense': 'https://depts.washington.edu/saswe/sdrips-sense/'
    - 'sDRIPS-Ukulima': 'https://depts.washington.edu/saswe/sdrips_ukulima/'
- Development:
    - 'Recent Adjustments': 'Development/RecentAdjustments.md'
    - 'Patch Notes': 'Development/PatchNotes.md'
    - 'Developer Version': 'Development/Developer_Version.md'
- Contact:
    - 'Contact': 'Contact/contact.md'
- Disclaimer:
    - 'Disclaimer': 'Disclaimer/disclaimer.md'

