precipitation: # To check the latest version go to https://jsimpsonhttps.pps.eosdis.nasa.gov/imerg/gis/early link 
    # You can view the prefix and suffix by hovering over the file names, or by copying a file link and pasting it into your browser to see the prefix and suffix details.
  base_urls:
    before: "https://jsimpsonhttps.pps.eosdis.nasa.gov/imerg/gis/early/"
    year:   "https://jsimpsonhttps.pps.eosdis.nasa.gov/imerg/gis/"
    after:  "https://jsimpsonhttps.pps.eosdis.nasa.gov/imerg/gis/early/"

  file_pattern:
    prefix: "3B-HHR-E.MS.MRG.3IMERG." # E - is for early, and L - is for late.
    suffix: "-S233000-E235959.1410.V07B.1day.tif" # As an example, V07B is the version could be changed to V07D.
